title: Hindsight is 20/20
email: mailsrikar@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
        My recent experiences and experiments
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: mailsrikar
github_username:  srikard
google_analytics: UA-143897089-1

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
